---
- name: create console notification
  kubernetes.core.k8s:
    definition:
      apiVersion: console.openshift.io/v1
      kind: ConsoleNotification
      metadata:
        name: '{{ ansible_operator_meta.name }}-occ-banner'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        text: "{{title}}"
        color: "{{text_color}}"
        backgroundColor: "{{background_color}}"

- name: patch the console logo
  kubernetes.core.k8s_json_patch:
    api_version: operator.openshift.io/v1
    kind: Console
    name: cluster
    patch:
      - op: replace
        path: /spec/customization/customLogoFile/name
        value: "{{logo.config_map_name}}"
      - op: replace
        path: /spec/customization/customLogoFile/key
        value: "{{logo.config_map_key}}"