# permissions for end users to edit consolecustomizers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: consolecustomizer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ocp-console-customizer
    app.kubernetes.io/part-of: ocp-console-customizer
    app.kubernetes.io/managed-by: kustomize
  name: consolecustomizer-editor-role
rules:
- apiGroups:
  - ocp-console-customizer.dovid
  resources:
  - consolecustomizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocp-console-customizer.dovid
  resources:
  - consolecustomizers/status
  verbs:
  - get
