---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - console.openshift.io
      - operator.openshift.io
    resources:
      - consolenotifications
      - consoles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  ##
  ## Rules for ocp-console-customizer.dovid/v1alpha1, Kind: ConsoleCustomizer
  ##
  - apiGroups:
      - ocp-console-customizer.dovid
    resources:
      - consolecustomizers
      - consolecustomizers/status
      - consolecustomizers/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for ocp-console-customizer.dovid/v1alpha1, Kind: ConsoleCustomizerSkin
  ##
  - apiGroups:
      - ocp-console-customizer.dovid
    resources:
      - consolecustomizerskins
      - consolecustomizerskins/status
      - consolecustomizerskins/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules


