apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ocp-console-customizer.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: ConsoleCustomizer
      name: consolecustomizers.ocp-console-customizer.dovid
      version: v1alpha1
      description: Switch quickly between different theme and skin for OCP Console.
      displayName: OCP Console Customizer

      specDescriptors:
      - description: Whether you want to enable or disable the application of skin on the OCP Console.
        displayName: Enable skin system
        path: enableSkin
        x-descriptors:
          - 'urn:alm:descriptor:com.tectonic.ui:booleanSwitch'
      - description: >-
          You may defined any number of skin using the ConsoleCustomizerSkin kind, and activate one here.
        displayName: Select the skin you want to activate
        path: activeSkin
        x-descriptors:
          - 'urn:alm:descriptor:com.tectonic.ui:fieldDependency:enableSkin:true'
          - 'urn:alm:descriptor:com.tectonic.ui:selector:consolecustomizerskins.ocp-console-customizer.dovid:v1alpha1:ConsoleCustomizerSkin'
        

    - kind: ConsoleCustomizerSkin
      name: consolecustomizerskins.ocp-console-customizer.dovid
      version: v1alpha1
      description: Skin definition for OCP Console Customizer
      displayName: Console Customizer Skin

      specDescriptors:
      - description: >-
          Any string you want to display on the top bar of the console. Usually <CustomerName> - <ClusterDescription> (Red Hat - Hub Cluster)
        displayName: Top Bar Title
        path: title
      - description: "Use an HEX color format, #FAFAFA"
        displayName: Top Bar Text Color
        path: textColor
      - description: "Use an HEX color format, #FAFAFA"
        displayName: Top Bar Background Color
        path: backgroundColor
      - description: >-
          A base64 representation of the logo you want to show at top right corner of the console.
        displayName: Base64 Logo
        path: logo
  description: >-
    This operator is for Red Hat internal, it is used to apply skin on OCP Console.
  displayName: OCP Console Customizer
  schema: olm.package
  icon:
  - base64data: "iVBORw0KGgoAAAANSUhEUgAAAHgAAAB5CAYAAADyOOV3AAAAAXNSR0IArs4c6QAAA9pJREFUeF7tnTFLXEEUhWfExl1YlrWL7ra2DwkLvuZZWKfIDwjW8SdY7Bb5A4uIpeQvuGUWspZ2aRLwpU8tGKwkT0y/M+DlMMzw2S5vVu6555x7512vvlss5k74s1oum6u2vVV9xeFo1Oz1erLzT+u6ceOx7Hx1fPx/gL2fqQBY3dysL+/vj1Xnv9/dXY/7fdn5n46O1m4ykZ2vjg8ARzIPgCMBUmcoDA4DAINhsM09YXA4fur4wGAYDIOpogM5oJYgiiyKLJME0SbRJpkSSK1wFFkUWaYEdeoMxYNjHnxxMXNdJ3vhAMCp+2AADiKQf5EFwABscWEkGom25I+jyKLIMiUQHsxFhymB1BbmO4osiixLiqozFA/Ggy356fBgPNiUQGqF899OTr6bfsPIwz8fHqq/z88/VN9xPp1WbjCQnf+rbas/T0+y89Xx8R8nk/m/rpPNReOR4dRWxweAC7cYAAZgm3uqJSj3KlcdHxgMg2Fwzn88B4NhMAyGwYEcUBcRFFmRu2guOtJOXKgJgAfjwXhw1h78YX9/tuW9bC5aLUF4cMSDAbhwDwZgADaZMBKd+HUhDIbBMDjjRW4eBsNgGAyDN+cARRZFlkkhuOjgosOUQOq5ZbXC+e7sTDoXvbi7q34/Psrmij8fHFTvdnZk5w+Hw8ptb8vOV8eHLTsRfuduAQAMwCYLY41S4vfNMBgGw2C2zQZyIPc2gyIrsceo+0gABmCTh6kVjiKLIsuUoLRJiRUOBsNgGJx3m8QitGAG519FAzAAW0Ra3QbQB0de+LOrMhwgJDpxGwCDYbDFYdhVGYseHpx27pp90cVfdNAm0SbFZDj0ORKNRFvyh/+6Eoke+6IjAWJfdCRA9KnhAKnjwxqlwi9qABiATTUQRVBiC4PBMBgGZ73pjmWkaS8iqKILvysGYAA2eSRFFkWWKYFok2iTbAmU+8yU3IPZdFd4FQ3AAGzSULUEIdGRqUoYDINhMMtIN+cAEp34hT8SjUQj0Ug0Ev1WFqgtjJX+pd9F48GFe/CXqpLuiz6fTis3GMj2Lec+t6yOj7+u6/mW97O3ekjsOW6awhFSxweAE7/OA+DCiyAABuCYCwY/R6KRaFMCZb/jQn0RgUQj0SaGIdFItCmBkOhI+JBoJNrEMCQaiTYlEBKdWqK/1vXMeT+3wbj5abXHsKYpjJwH4LQzU2oCAHDpHgyDYbDJntUShAfjwaYEzf4uGolGok0MQKITj+zAYBgMg/v9Y1MQAg+rFY4+uPQ++HVsVpWdr+ee1nXjxuNb1Xeslsvmqm1l5x+ORs1eryc7Xx2fF8l+Zpby6919AAAAAElFTkSuQmCC"
    mediatype: "image/png"
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ocp
  - console
  - skin
  - theme
  - redhat
  links:
  - name: Ocp Console Customizer
    url: https://ocp-console-customizer.domain
  maintainers:
  - email: dcuerrie@redhat.com
    name: David Cuerrier
  maturity: alpha
  provider:
    name: DC
  version: 0.0.0
