---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: consolecustomizers.ocp-console-customizer.dovid
spec:
  group: ocp-console-customizer.dovid
  names:
    kind: ConsoleCustomizer
    listKind: ConsoleCustomizerList
    plural: consolecustomizers
    singular: consolecustomizer
    shortNames: 
      - occ
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ConsoleCustomizer is the Schema for the consolecustomizers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of ConsoleCustomizer
            type: object
            properties:
              title:
                description: Title that will be shown in the notification bar
                type: string
              textColor:
                description: Text color of the notification bar
                type: string
                pattern: '^#[A-F a-f 0-9]{6}$'
              backgroundColor:
                description: Background color of the notification bar
                type: string
                pattern: '^#[A-F a-f 0-9]{6}$'
              logo:
                description: Title that will be shown in the notification bar
                type: string
          status:
            description: Status defines the observed state of ConsoleCustomizer
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    additionalPrinterColumns:
    
    - name: Title
      type: string
      description: Title that will be shown in the notification bar
      jsonPath: .spec.title

    served: true
    storage: true
    subresources:
      status: {}
